### ISSUE TITLE
hw010 ready for grading!

### ISSUE THREAD

**Issue by yanchaoluo** [yanchaoluo/STAT545-hw-Luo-Yanchao#9]
@vincenzocoia @gvdr @ksedivyhaley @JoeyBernhardt @mynamedaike @pgonzaleze @derekcho

+ [hw10 file](https://github.com/yanchaoluo/STAT545-hw-Luo-Yanchao/tree/master/hw10)

+ [hw10 markdown](https://github.com/yanchaoluo/STAT545-hw-Luo-Yanchao/blob/master/hw10/hw10_Luo_Yanchao.md)

Thanks! 😄

**Comment by CassKon** [comment]
# Homework 10
* Suppress the start up messages to make your assignment cleaner using  “```{r message=FALSE}”
* More comments throughout your code would make it easier to follow
* Nice formatting on the tables 
* It was nice that you made data frames so that the example is reproducible
* Overall it looks good. I am impressed that you decided to tackle all three approaches for this homework although maybe tackling one and being more thorough would have been more beneficial.
* Very well done nonetheless and hope that the end of your semester goes well!

**Comment by heathersummers** [comment]
Hi,

It is really impressive that you worked on all three ways to get data from the web into R. I would suggest adding more commenting throughout the document to make it easier for the reviewer to follow and understand the code. For the first section where you made API queries using `httr`, the dataframe with the movies Thor and Spiderman included lots of important information but I did find it much easier to read when you created the subset of the data. Awesome job on the second section where you scraped data from the Spiderman movie. I was a little confused why the points in the plot were coloured by year and I think the plot would have benefited from either a legend or description indicating what movies were included in the plot. In addition, I would suggest adding a title to the plot and re-labeling the y-axis title. Great work on completing the first prompt for the third section where you used an R package that wraps an API, it was great to see you combined the data from `gapminder` and `geonames` and computed a plot of population vs. year for each continent. Lastly, I would check out this [link](https://stackoverflow.com/questions/13090838/r-markdown-avoiding-package-loading-messages) as it could be helpful if you are interested in hiding the results, messages, and warnings that come up when you load packages in R Markdown. Overall good work on the assignment and hope you enjoy your holidays.

Heather
